package io.oliverj.chat.client.ui;

import io.oliverj.chat.client.network.MessagePublisher;

import javax.swing.*;
import java.awt.*;

public class ChatScreen extends JFrame {
    private JPanel contentView;
    private JTextField messageBox;
    private JLabel chatView;

    public ChatScreen() {
        setTitle("Chat App");
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setContentPane(contentView);
        pack();

        setLocationRelativeTo(null);

        messageBox.addActionListener(e -> {
            String message = messageBox.getText();

            MessagePublisher.send(message);
        });

        MessagePublisher.registerHandler(msg -> {
            chatView.setText(chatView.getText() + "\n" + msg);
        });
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        contentView = new JPanel();
        contentView.setLayout(new BorderLayout(0, 0));
        messageBox = new JTextField();
        contentView.add(messageBox, BorderLayout.SOUTH);
        chatView = new JLabel();
        chatView.setAutoscrolls(true);
        chatView.setText("");
        chatView.setVerticalAlignment(1);
        chatView.setVerticalTextPosition(1);
        contentView.add(chatView, BorderLayout.WEST);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return contentView;
    }

}
